
// This file has been generated by the GUI designer. Do not modify.
namespace PSerpisAd
{
	public partial class WindowHelper
	{
		public virtual void Build ()
		{
			// Action group PSerpisAd.WindowHelper
		}
	}
}
